language: erlang
otp_release:
  - 17.4
elixir:
  - 1.0.4
before_script:
  - export SCRIVENER_DB_USER=postgres
  - mix local.hex --force
  - mix deps.get --only test
  - MIX_ENV=test mix scrivener.db.reset
script: mix test
